#!/bin/bash
set -eu -o pipefail

basedir=$(cd "$(dirname "$0")" && pwd -P)
cd "$basedir"

mkdir -p reference/
#   These are just for developer reference; we don't use this code in
#   our repo. Thus we don't use a submodule because we don't want or
#   need to lock the version to a specific commit.
[[ -d reference/book-code ]] || {
    rcbc=https://github.com/gergoerdi/retroclash-book-code
    git clone -o upstream  "$rcbc" reference/book-code
}
[[ -d reference/clash-prelude ]] || {
    repo=https://github.com/clash-lang/clash-prelude
    git clone -o upstream  "$repo" reference/clash-prelude
}

stack build --test
